name: Assign Reviewer
# for pull requests
on:
  pull_request:
    types: [opened]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Assign Reviewer
        uses: peter-evans/create-pull-request@v3.8.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "Assigning reviewer to pull request"
          title: "Assigning reviewer to pull request"
          body: "Please review this pull request."
          branch: "add-reviewer-to-pull-request-${{ github.event.pull_request.number }}"
          labels: "review-requested"
          reviewers: "JohnL3"
