name: Assign Reviewer
# for pull requests
on:
  pull_request:
    types: [opened]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewer
        uses: peter-evans/create-pull-request@v3.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Assigning reviewer to pull request"
          title: "Assigning reviewer to pull request"
          body: "Please review this pull request."
          branch: "add-reviewer-to-pull-request-${{ github.event.pull_request.number }}"
          labels: "review-requested"
          reviewers: "NielC"
